# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'xmls/settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtWidgets


class UiSettings(object):
    def setupUi(self, Settings, parameters):
        Settings.setObjectName("Settings")
        # Settings.resize(233, 136)
        self.grid = QtWidgets.QGridLayout(Settings)
        self.labeles = dict()
        for i, key in enumerate(parameters.keys()):
            # create label
            label = self.new_label(Settings)
            self.grid.addWidget(label, i, 0, 1, 1)
            label.setText(key)
            # create line edit
            line_edit = self.new_line_edit(Settings)
            self.grid.addWidget(line_edit, i, 1, 1, 1)
            self.labeles[key] = (label, line_edit)
        self.cancel_button = QtWidgets.QPushButton()
        self.grid.addWidget(self.cancel_button, len(parameters), 0, 1, 1)
        self.cancel_button.setText("Cancel")
        self.apply_button = QtWidgets.QPushButton()
        self.grid.addWidget(self.apply_button, len(parameters), 1, 1, 1)
        self.apply_button.setText("Apply")

    def new_label(self, Settings):
        label = QtWidgets.QLabel(Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(label.sizePolicy().hasHeightForWidth())
        label.setSizePolicy(sizePolicy)
        return label

    def new_line_edit(self, Settings):
        line_edit = QtWidgets.QLineEdit(Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(line_edit.sizePolicy().hasHeightForWidth())
        line_edit.setSizePolicy(sizePolicy)
        return line_edit
